swagger: '2.0'
info:
  title: Bank Argent proposed API documentation
  description: Phase2-Transactions proposed API model
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: Request for fetching all user's Transactions
      parameters:
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/ApiResponseTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: Request for fetching user specific account's Transactions
      parameters:
        - in: path
          type: integer
          name: accountId
          description: Id of account to return transactions from
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/ApiResponseTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: Request for fetching Transaction's additional informations
      parameters:
        - in: path
          type: integer
          name: transactionId
          description: Id of transaction to return additionnal informations from
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction additional informations retrieved successully
          schema:
            $ref: '#/definitions/ApiResponseAdditionalInfos'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: Request for adding Transaction's additional informations
      parameters:
        - in: path
          type: integer
          name: transactionId
          description: Id of transaction
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: addtionnal informations of created transcation
          schema:
            $ref: '#/definitions/TransactionAdditionalInfos'
          required: true
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: Transaction additional informations created successully
          schema:
            $ref: '#/definitions/ApiResponseAdditionalInfos'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: Request for modifying Transaction's additional informations
      parameters:
        - in: path
          type: integer
          name: transactionId
          description: Id of transaction
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: addtionnal informations of created transcation
          schema:
            $ref: '#/definitions/TransactionAdditionalInfos'
          required: true
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: Transaction additional informations modified successully
          schema:
            $ref: '#/definitions/ApiResponseAdditionalInfos'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: Request for deleting Transaction's additional informations
      parameters:
        - in: path
          type: integer
          name: transactionId
          description: Id of transaction
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: Transaction additional informations deleted successully
          schema:
            type: object
            properties:
              ApiResponse:
                $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':        
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: object
    properties:
      id:
        type: integer
        description: transaction unique identifier
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      ammount:
        type: number
        description: transaction ammount
      balance:
        type: number
        description: account balance after transaction

  TransactionAdditionalInfos:
    type: object
    properties:
      transactionType:
        type: string
        description: transaction type
        enum: [Electronic, Card, Withdrowing, Other]
      category:
        type: string
        description: transaction category
        enum: [Food, Health, Hobbies, Shopping, Other]
      Notes:
        type: string
        description: transaction notes

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
   
  ApiResponseTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transactions'
        
  ApiResponseAdditionalInfos:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/TransactionAdditionalInfos'
